spring.application.name=pnn-backend

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pnn-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (테이블 없음 — validate 시 연결만 확인)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Python AI Server URL
ai.server.url=http://localhost:8000
